version: "3"
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:5.5.1"
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafkadocker
  kafka:
    # https://hub.docker.com/r/wurstmeister/kafka
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 39092:39092
    volumes:
      - /Users/taoxiaoyan/kafka-logs:/var/lib/kafka/data
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,DOCKERNETWORK://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DOCKERNETWORK:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    networks:
      - kafkadocker

networks:
  kafkadocker:
    driver: bridge